#This plugin is made by TheMachuPichu for everyone
#It works between spigot version 1.8
#This plugin can't be reloaded

#DebugMode sends a message to the console each time an event is called
#/!\ The debugmode can spam the console /!\
DebugMode: false

#Enable or disable color message in the console
ColorConsole: true

Worlds:
  DefaultNumber: 2
  Increase: 2
  Title: "CTS-"
  Copy: "world"

##############################################
# __  __  ___  ____  _   _ _     _____ ____  #
#|  \/  |/ _ \|  _ \| | | | |   | ____/ ___| #
#| |\/| | | | | | | | | | | |   |  _| \___ \ #
#| |  | | |_| | |_| | |_| | |___| |___ ___) |#
#|_|  |_|\___/|____/ \___/|_____|_____|____/ #
##############################################
#Enable or disable modules

#After update, reload the plugin or restart the server

CTS:
  Play: true
  Kits: true

###########################################################################
#  ____ ___  _   _ _____ ___ ____ _   _ ____      _  _____ ___ ___  _   _ #
# / ___/ _ \| \ | |  ___|_ _/ ___| | | |  _ \    / \|_   _|_ _/ _ \| \ | |#
#| |  | | | |  \| | |_   | | |  _| | | | |_) |  / _ \ | |  | | | | |  \| |#
#| |__| |_| | |\  |  _|  | | |_| | |_| |  _ <  / ___ \| |  | | |_| | |\  |#
# \____\___/|_| \_|_|   |___\____|\___/|_| \_\/_/   \_\_| |___\___/|_| \_|#
###########################################################################
#After update, restart the server

#Setting up the game
Game:
  MaxPlayers: 16
  MinPlayers: 8
  #Time after spawn when the player is invincible in second
  Invincibility: 5
  TeamSizeZone: 5
  EndGameTime: 10
  WaitTime: 30
  ScoreBoard:
    Update: 1

GUI:
  Kits:
    Title: "Menu des kits"
    Size: 27
  Teams:
    Title: "Choisis ta team"
    Size: 9
    Items:
      BlueTeam:
        Material: BLUE_BANNER
        Title: "Team bleu"
        Lore: [ ]
        Location: 4
      RedTeam:
        Material: RED_BANNER
        Title: "Team rouge"
        Lore: [ ]
        Location: 6

#Setting up customs items in the lobby
LobbyItems:
  StartItem:
    Material: DIAMOND_AXE
    Title: "Start Game"
    Lore: [ ]
    Location: 4
    Command: "CTS play"
  KitsItem:
    Material: CHEST
    Title: "Kits"
    Lore: []
    Location: 5
    Command: "CTS kits"

#Config the AutoDeleter which allows you to automatically delete some blocks you own
AutoDelete:
  #List of all blocks can be delete
  Blocks:
    - STONE
    - DIRT
  #Time before deleting block in second
  Time: 10